### ISSUE TITLE
PowerShell Crescendo should have a versioned schema

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/Crescendo#112]
PowerShell Crescendo should have a versioned schema to support future updates without breaking previous versions.  Currently, this is not the case.  We are discussing the format and will add notes here, however it should follow a standard schema versioning format including the date of release.

**Comment by JamesWTruher** [comment]
fixed in cd196632061446a25ead69dc86e16202d6606368 (branch SchemaVersions)
