### ISSUE TITLE
Question on Parameter definiton "DefaultValue"

### ISSUE THREAD

**Issue by RStadlmair** [PowerShell/Crescendo#114]
Hi all !

The current schema (preview-4)  says this about setting a default value on a parameter:
```JSON
"DefaultValue": {
            "type": "string",
            "description": "The default value for the parameter."
          }
```

Now if i have a [switch] parameter like "-nobannner" in my schema as below
```JSON
{
   "ParameterType": "Switch",
   "Name": "NoBanner",
   "OriginalName": "-nobanner",
   "DefaultValue" : **"????"**
   "ParameterSetName": ["Default"],        
}

```

, how do i use the [string] value for the default value of -nobanner ?

i tried:

- true
- $true
- -nobanner

already
Thx / R.

**Comment by JamesWTruher** [comment]
since the parameter is a switch type the default value is expected to not be present when the parameter is not present. What behavior are you looking for here?

**Comment by RStadlmair** [comment]
In fact i´d like to have "-nobanner" turned on by default with a switch parameter.

As this is described in a JSON, my first thought was "true"/"false" if the parametertype is [bool] or [switch].

**Comment by theJasonHelmick** [comment]
If you have a default value for a parameter, then I don't think you want to mark it as a switch.

**Comment by JamesWTruher** [comment]
i _think_ what you want is a `-banner` which then turns the banner on, otherwise it's off. yes?

**Comment by RStadlmair** [comment]
James, this is exactly what - i guess also others - want. By default, when calling the exe file, the "-banner" parameter should not be used.
