### ISSUE TITLE
Sysinternals as example/community repo

### ISSUE THREAD

**Issue by RStadlmair** [PowerShell/Crescendo#125]
Hi Crescendo Team !

Every admin in the windows world loves sysinternals. If we would have Powershell Crescendo commandlets around sysinternal command, this may give Crescendo a massive push in adaption.

Would be great if the powershell team could host a repo with a few examples and the community may contribute to a PSsysinternals module based on Crescendo. 

To be discussed/R.

**Comment by theJasonHelmick** [comment]
Thank you @RStadlmair for the suggestion!  Crescendo is a framework to help accelerate the process of creating cmdlets for cli commands. It is my hope that the community will use Crescendo for Sysinternals or any commands that they want a cmdlet experience with structured data (Objects).  While we aren't focused on releasing a specific module for SysInternals (which we all love), I would certainly encourage you to use Crescendo to build one.  Maybe even share it on the PowerShell Gallery with the rest of the community.

**Comment by sdwheeler** [comment]
@adamdriscoll has started one https://github.com/adamdriscoll/sysinternals
