### ISSUE TITLE
Handling parameters that are Mandatory in some parameter sets, but not others

### ISSUE THREAD

**Issue by WillPittenger** [PowerShell/Crescendo#132]
If you look at the `[Parameter]` attribute, you duplicate it for all parameter sets.  So a parameter could be position=0 in one set and position=3 in another.  Plus, the Mandatory value could change.  You need to use that to tell PowerShell which set to use.  Unfortunately, Crescendo doesn't seem to support that.  The way I read it, the parameter set is an array, but those share position and mandatory values.  So how does PowerShell know which parameter set is being used at runtime?

**Comment by steviecoaster** [comment]
Are you looking to have this be more this syntax:

```json
"ParameterSetName" : [
    {
        "Name": 'Default'
        "Mandatory": true
        "Position": 0
    }
]
````

It would take some additional logic, but I don't think that's outside the realm of possibility, and a _pretty decent_ way to handle it.

**Comment by WillPittenger** [comment]
Well, I was thinking of something matching the syntax you'd use in a PS script.

**Comment by sdwheeler** [comment]
Take a look at the JSON schema for Parameter. You can specify the ParameterSetName. Just create the same parameter definition multiple times for each parameter set.
