### ISSUE TITLE
How to add enum parameters

### ISSUE THREAD

**Issue by Swimburger** [PowerShell/Crescendo#138]
I have a parameters that only accepts a specific set of strings (debug, info, warning, etc.)
How do I create a parameter which validates an enum in Crescendo?
Preferably following the PascalCasing naming style, while being able pass it as a lowercase string to the original command.

**Comment by Swimburger** [comment]
Thank you, this is very helpful information. When I tried to use a PowerShell enum as the `ParameterType`, I don't think it would bundle the enum with the module. 
Would there be a way to inject the enum definition into the module generated by Crescendo?

**Comment by draproctor** [comment]
If you're looking for parameters that only accept certain strings, why not use the `[ValidateSet()]` parameter attribute?
