### ISSUE TITLE
Schema should have an extension

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/Crescendo#142]
When displaying the schema file in gitHub, the file is displayed without syntax coloring because there is no file extension. I suggest adding a `.json` extension when we next update the version Crescendo.

**Comment by michaeltlombardi** [comment]
@theJasonHelmick it _might_ be possible to add syntax highlighting in the meantime (ie without doing a release) by specifying an override in the `.gitattributes` file, per [this documentation](https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes) on `linguist`, the tool GitHub uses for syntax highlighting.

```gitattributes
Microsoft.PowerShell.Crescendo/schemas/* linguist-language=jsonc
```

**Comment by theJasonHelmick** [comment]
@michaeltlombardi -- I like your idea -- I think Jim does too -- we will investigate this.

**Comment by JamesWTruher** [comment]
that's generally not how versioned schemas are done - see https://json-schema.org/draft/2020-12/schema is the schema without extension

**Comment by theJasonHelmick** [comment]
@michaeltlombardi @JamesWTruher -- If the standard is to not have an extension, then lets not add one. I'll follow up with Mikey about other options.  Marking this issues as by design.
