### ISSUE TITLE
Dynamic element names and values

### ISSUE THREAD

**Issue by jasoth** [PowerShell/Crescendo#148]
I am trying to allow public properties to be defined on msiexec where the cmd element name can be dynamically specified via hashtable. This could also benefit from the option to specify the Gap character described in issue #32.
'msiexec /i <path_to_package> PROPERTY=VALUE PROPERTY2=VALUE2'

For example, this could look something like:
```
{
    "OriginalName": "",
    "Name": "PublicProperties",
    "ParameterType": "hashtable",
    "Mandatory": false,
    "Description": "Public Properties",
    "GapCharacter": "="
}
```

This would also be useful as a catch-all to specify additional cmd elements when you do not want to parameterize everything via Crescendo.

**Comment by JamesWTruher** [comment]
this can be done today by specifying the parameter type as `[string[]]` and then when invoking, you would construct these as expected:
`invoke-thing -publicproperties Property=Value,Property2=Value2` which is probably more similar to how you would actually invoke it natively

**Comment by theJasonHelmick** [comment]
@jasoth - thank you -- this issue has been answered as is being closed. Please feel free to reopen if further discussion is desired.
