### ISSUE TITLE
HelpInfoUri link in PSD1 file is broken,

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/Crescendo#149]
```PowerShell
HelpInfoUri = 'https://aka.ms/ps-modules-help'
```
Opening this link goes to https://pshelpprod.blob.core.windows.net/cabinets/ps-modules/ which reports "Blob not found"

**Comment by sdwheeler** [comment]
This is expected behavior. You cannot browse that location. `Update-Help` uses the **HelpInfoUri** to construct the full path to the HelpInfo.xml file.

**Comment by jhoneill** [comment]
Thanks Sean . Not sure if I *did* know that and I'd forgotten or  if  I always misunderstood what it was for
