### ISSUE TITLE
ApplyToExecutable is missing from the ParameterInfo definition in the JSON Schema File.

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/Crescendo#150]
If you it's available you can put it in the JSON, but intellisense won't suggest it if it isn't in the schema.

**Comment by JamesWTruher** [comment]
see #161

**Comment by theJasonHelmick** [comment]
Thank you @jhoneill -- This is added in pr [#161](https://github.com/PowerShell/Crescendo/pull/161)

**Comment by theJasonHelmick** [comment]
Thank you! Fixed/closed - in release: https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo/1.1.0-RC1
