### ISSUE TITLE
PSD file doesn't have link to the Repo or Licensing info

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/Crescendo#153]
So "Project Site" doesn't  appear when looking at the package on the PowerShell gallery

**Comment by theJasonHelmick** [comment]
Hey @jhoneill -- Can you be more specific about the what package and issue you are referring?

**Comment by jhoneill** [comment]
https://github.com/PowerShell/Crescendo/blob/master/Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd

There's no PSData section. If it's built with New-Modulemanifest  there are options to add them, IIRC that's where the Gallery gets its info from.

**Comment by JamesWTruher** [comment]
see #159

**Comment by theJasonHelmick** [comment]
Thank you @jhoneill -- this is added with pr https://github.com/PowerShell/Crescendo/pull/159

**Comment by theJasonHelmick** [comment]
Thank you! Fixed/closed - in release: https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo/1.1.0-RC1
