### ISSUE TITLE
Cannot find function when generating module from Schema file

### ISSUE THREAD

**Issue by steviecoaster** [PowerShell/Crescendo#166]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo)
- [X] Search the existing issues.

### Steps to reproduce

I've created a function for parsing the output of handle.exe to help improve an existing Crescendo module from Adam Driscoll. You can find this module [here](https://github.com/adamdriscoll/sysinternals).

I've written my function and loaded it into my running session, and can confirm that doing something like `handle.exe | Read-HandleOutput` produces expected results for me.

I've defined the OutputHandler as such in my schema:

```json
"OutputHandlers": [
        {
          "ParameterSetName": "default",
          "Handler": "Read-HandleOutput",
          "HandlerType": "Function",
          "StreamOutput": false
        }
      ]
```

I'm receiving the following when attempting to create the module from the schema:

![image](https://user-images.githubusercontent.com/8674240/181620418-062b1019-5e3a-4399-b664-73b536633cb7.png)

I've used this process for other Crescendo modules I've worked on in the past with success, so I'm not entirely sure what I'm missing here?

Gist of the json file being used to produce this module is at https://gist.github.com/steviecoaster/5926d335d8008bfd4d9ab7b5ca454a92

### Expected behavior

```console
I expect the module to be produced, and consumable for use.
```

### Actual behavior

```console
See error in description
```

### Environment data

```PowerShell
PowerShell Version info:



Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

1.0.0

### Visuals

![2022-07-28_15-27-50 (1)](https://user-images.githubusercontent.com/8674240/181621739-9b1f98bd-bc7d-4a98-bffe-61cd3d81ea2d.gif)

**Comment by theJasonHelmick** [comment]
@steviecoaster - If you get a chance, can you confirm Jim's response -- We believe there is an error message that is being displayed indicating that the function can not be found.  Load the function, then run Export-CrescendoModule and it should work as expected.

**Comment by steviecoaster** [comment]
@theJasonHelmick @JamesWTruher my gif shows that the function is loaded. I try to export the module, get the error, then I run the function directly to show that it has been in fact loaded in the session, but it is never picked up by Crescendo.

This works for other Crescendo modules I've done. Just...not this one. And I am terrible confused by it!

**Comment by JamesWTruher** [comment]
@steviecoaster  could you also include the output of the following:
```powershell
get-command -all Read-HandleOutput
```
