### ISSUE TITLE
In the comment at the beginning of the generated module add the current version of the Crescendo module.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Crescendo#167]
### Summary of the new feature / enhancement

In the comment at the beginning of the generated module add the current version of the Crescendo module and/or the version of the schema used  :

```
 # Module created by Microsoft.PowerShell.Crescendo
```

### Proposed technical implementation details (optional)

```
# Module created by Microsoft.PowerShell.Crescendo version x.y.z
#or
# Module created by Microsoft.PowerShell.Crescendo version x.y.z, schemas version x.y.z
```

**Comment by theJasonHelmick** [comment]
@LaurentDardenne  - Wonderful suggestion -- we plan to implement as below:

# Module created by Microsoft.PowerShell.Crescendo
# Version: 1.1.0
# Schema: https://aka.ms/PowerShell/Crescendo/Schemas/2021-11

**Comment by theJasonHelmick** [comment]
Thank you! Fixed/closed - in release: https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo/1.1.0-RC1
