### ISSUE TITLE
Need No Handler / Post Processing At All

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/Crescendo#172]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo)
- [X] Search the existing issues.

### Steps to reproduce

I am attempting to convert [pastel](https://github.com/sharkdp/pastel) to PowerShell using Crescendo. `pastel` is a powerful color tool that supports things like:

```
pastel color blue | pastel mix red | pastel lighten 0.2 | pastel format hex
```

But the Crescendo handler flattens my output

![image](https://user-images.githubusercontent.com/8278033/188348720-8941fdc5-1777-4593-bb8e-a453fb7ceb51.png)

I'm guessing that any sort of post-processing flattens it bc pastel just needs just the `hsl(240,100.0%,50.0%)` in a pipe.

![image](https://user-images.githubusercontent.com/8278033/188349501-f682bb7c-39a5-40a4-ac80-da58ec0a66bb.png)

### Expected behavior

```console
The ability to output without additional processing.
```

### Actual behavior
Some sort of processing occurs somewhere around

```console
    $__handlerInfo = $__outputHandlers[$PSCmdlet.ParameterSetName]
    if (! $__handlerInfo ) {
        $__handlerInfo = $__outputHandlers["Default"] # Guaranteed to be present
    }
    $__handler = $__handlerInfo.Handler
    if ( $PSCmdlet.ShouldProcess("pastel $__commandArgs")) {
    # check for the application and throw if it cannot be found
        if ( -not (Get-Command -ErrorAction Ignore "pastel")) {
          throw "Cannot find executable 'pastel'"
        }
        if ( $__handlerInfo.StreamOutput ) {
            & "pastel" $__commandArgs | & $__handler
        }
        else {
            $result = & "pastel" $__commandArgs
            & $__handler $result
        }
    }
```

I tried to just return `& "pastel" $__commandArgs` and it worked. Assigning it to a variable and returning that or or even putting a `return` in front flattened it.

### Error details

```console
No errors
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

1.0.0

**Comment by sdwheeler** [comment]
@potatoqualitee If you just want output from `pastel` you don't need to define an output handler. The purpose of the output handler is to convert output from the original command to a PowerShell object.

**Comment by theJasonHelmick** [comment]
Hi @potatoqualitee - thanks for the issue! It appears that Pastel is ONLY outputting the HSL(240,100....etc). You can check in Bash, `pastel color blue | cat`.  We investigated the pastel source code and it appears that there are some unique behaviors for pastel when it's in interactive mode.   example: `pastel color blue` - pastel knows to display to screen - `pastel color blue | %{$_}` causes pastel to restrict the output to a string HSL:240,100....  Basically, for pastel to display the desired graphic output, it needs to pipe results back to the pastel command.  

Essentially, Crescendo is not flattening the output, pastel is flatting the output because it knows it's piping to something.  This is not a scenario that Crescendo currently supports. Crescendo supports sending arguments to a command, not piping input to the command. However, the workaround you might try is: 
1. The output handler is set to stream. 
2. Your output handler could look like this: `$input | pastel lighten 0`

 We are exploring the idea of creating a handler bypass for scenarios similar.  In this case, you will still have the problem of piping input while accepting arguments on the command at the same time.

**Comment by potatoqualitee** [comment]
Thanks for looking into this @theJasonHelmick. I understand that pastel is flattening it but only if it's being processed. Crescendo in this case, is doing too much work for me.  Ultimately, I solved this by rewriting Crescendo's code in my build.ps1. 

The simplest way to do this was to set my Handler to `$true` then telling the code that if Handler is set to true, execute `& "pastel" $__commandArgs` instead of either `& "pastel" $__commandArgs | & $__handler` or `$result = & "pastel" $__commandArgs`

```
if ( $__handlerInfo.StreamOutput ) {
            & "pastel" $__commandArgs | & $__handler
        } elseif ($__handlerInfo.Handler) {
            & "pastel" $__commandArgs
        } else {
            $result = & "pastel" $__commandArgs
            & $__handler $result
        }
```

Setting the output handler to Stream still overprocessed my command and did not solve my issue.

**Comment by JamesWTruher** [comment]
I fiddled this a bit and came up with something that may serve in a different way.
![pastel-1](https://user-images.githubusercontent.com/10214008/193935976-990ff52a-2078-4ef3-a2e6-36f84dc8f98a.gif)
```json
{
   "$schema": "https://aka.ms/PowerShell/Crescendo/Schemas/2021-11",
   "Commands": [
        {
          "Verb": "new",
          "Noun": "PastelColor",
          "OriginalName": "pastel",
          "Platform": [
            "Linux",
            "MacOS"
          ],
          "SupportsShouldProcess": false,
          "SupportsTransactions": false,
          "NoInvocation": false,
          "Parameters": [
            {
              "ParameterType": "string",
              "Position": 2147483647,
              "Name": "Color",
              "OriginalName": "color",
              "ApplyToExecutable": false,
              "Mandatory": true,
              "OriginalPosition": 0,
              "ValueFromPipeline": false,
              "ValueFromPipelineByPropertyName": false,
              "ValueFromRemainingArguments": false,
              "NoGap": false
            }
          ],
          "Examples": [],
          "OutputHandlers": [
            {
              "ParameterSetName": "Default",
              "Handler": "$input | pastel color",
              "HandlerType": "inline",
              "StreamOutput": true
            }
          ]
        },
        {
          "Verb": "New",
          "Noun": "PastelMix",
          "OriginalName": "pastel",
          "Platform": [
            "Linux",
            "MacOS"
          ],
          "SupportsShouldProcess": false,
          "SupportsTransactions": false,
          "NoInvocation": false,
          "Parameters": [
            {
              "ParameterType": "string",
              "Position": 2147483647,
              "Name": "Mix",
              "OriginalName": "mix",
              "ApplyToExecutable": false,
              "Mandatory": true,
              "OriginalPosition": 4,
              "ValueFromPipeline": false,
              "ValueFromPipelineByPropertyName": false,
              "ValueFromRemainingArguments": false,
              "NoGap": false
            },
            {
              "ParameterType": "object",
              "Position": 2147483647,
              "Name": "Color2",
              "OriginalName": "",
              "ApplyToExecutable": false,
              "Mandatory": true,
              "OriginalPosition": 5,
              "ValueFromPipeline": true,
              "ValueFromPipelineByPropertyName": false,
              "ValueFromRemainingArguments": false,
              "NoGap": false
            }
          ],
          "Examples": [],
          "OutputHandlers": [
            {
              "ParameterSetName": "Default",
              "Handler": "$input | pastel color",
              "HandlerType": "inline",
              "StreamOutput": true
            }
          ]
        }
   ]
}
```

**Comment by potatoqualitee** [comment]
awesome! will take this and run with it 🥳
