### ISSUE TITLE
Make generated proxies compatible with Windows PS 5.1

### ISSUE THREAD

**Issue by gaelcolas** [PowerShell/Crescendo#18]
The current Proxies are only PS7+, and I think it's only because of the use of the ternary operator.

I know it's early days but filing in to keep track.

**Comment by Windos** [comment]
Reading the [announcement blog post](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-1/) indicates that Win PS 5.1 support is available today, but that's not the case with the version up on the gallery atm.

![image](https://user-images.githubusercontent.com/6955786/101709212-f19d1680-3af3-11eb-8446-628d0873d538.png)

Might pay to small print that to say "eventually."

**Comment by jdhitsolutions** [comment]
I wonder if this should even be an issue. Would it be so terrible if this module only worked with PowerShell 7? Windows PowerShell doesn't have to go away, but it also doesn't mean that every new development needs to run on it .

**Comment by lucdekens** [comment]
Since not all modules in the PSGallery are supported in post-PSv5.1 environments, I'm still strongly in favor of making the generated modules PSV5.1 compatible.

It is only 1 ternary operator after all.

**Comment by theJasonHelmick** [comment]
We did an update (0.4.1) to remove the ternary operator form the generated modules. That should help with WinPS5.1 Compat.  I think its important to support existing on-prem automation which still supports a lot of WinPS5.1.  Note, that if the author mistakenly writes a ternary operator into the output handler, this is still going to be generated into the proxy module with the ternary.  We are thinking of ways to improve the output handler and look forward to ideas.
