### ISSUE TITLE
Crescendo should probably set `$PSNativeCommandUseErrorActionPreference = $false`

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/Crescendo#186]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo)
- [X] Search the existing issues.

### Steps to reproduce

because setting `$PSNativeCommandUseErrorActionPreference = $true` will result in an additional error record being produce in the case of an error, crescendo should probably set this variable explicitly now that we handle error output as part of `push-crescendoerror`. Perhaps it should be settable on a command by command basis (add it to the schema for a command???)

### Expected behavior

```console
a single error
```

### Actual behavior

```console
2 errors
```

### Error details

```console
PS> /bin/ls a
ls: a: No such file or directory
NativeCommandExitException: Program "ls" ended with non-zero exit code: 1.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.0-daily20221207.1
PSEdition                      Core
GitCommitId                    7.3.0-daily20221207.1
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

all

**Comment by theJasonHelmick** [comment]
Thank you! Fixed/closed - in release: https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo/1.1.0-RC1
