### ISSUE TITLE
Why isn't my parser a hidden function?

### ISSUE THREAD

**Issue by DennisL68** [PowerShell/Crescendo#195]
### Summary of the new feature / enhancement

When I list available commands in my generated module using `get-command -module <newmodule>`, the functions I use for parsing is available as PowerShell functions as well...

Shouldn't those be hidden from export by only exposing the Commands defined in the json file using Export-ModuleMember?

**Comment by theJasonHelmick** [comment]
Hi @DennisL68 -- Thank you for the issue.  You raise an interesting point.  First, you can control this in PowerShell a couple of ways today.  In a module .psm1 you can use the `Export-ModuleMember` as described here: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/export-modulemember?view=powershell-7.3

However, Crescendo created a module manifest (.psd1) that provides these controls with `FunctionsToExport`. Here are the docs: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_module_manifests?view=powershell-7.3#functionstoexport

The interesting point you raised - should we pre-populate the `FunctionsToExport` for you -- There are some drawbacks to this, such as accidentally hiding functions that you may wish exposed.  We decided to leave control up to you - as it is in PowerShell, to decide which functions you want exported and which ones you want hidden.

**Comment by DennisL68** [comment]
Yes, but I can't think of any reason why the function specified as the output parser should be made public for the user of the command produced?

Now, I am aware of the feature of not overwriting the PSD when rebuilding the Crescendo-module, so that will of course work.

**Comment by theJasonHelmick** [comment]
Thank you for the feedback!
