### ISSUE TITLE
Support mandatory parameters

### ISSUE THREAD

**Issue by DennisL68** [PowerShell/Crescendo#198]
### Summary of the new feature / enhancement

As a PowerShell scripter
I'd like to make sure that required parameters is present
that otherwise would render an error if running the original command without them being present

### Proposed technical implementation details (optional)

Add a switch that would mark a specific parameter as Mandatory.

**Comment by DennisL68** [comment]
Is that option part of the 2022-06 pre-release XML schema?

**Comment by theJasonHelmick** [comment]
Yes - it has been since the early beta
