### ISSUE TITLE
Can we talk about PowerShell script ... style?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/Crescendo#29]
Hopefully without offending anyone. Let's just call this a code review. I believe that any tool which generates code should generate the _best possible_ code, because there are always going to be new users that start their experience using your code generator, and then learn their style from that code.

Here, for example, is the _current_ output from the sample `apt` from the blog post (after I fixed the json quotes):

```PowerShell
# Module created by Microsoft.PowerShell.Crescendo
Function Get-InstalledPackage
{
[CmdletBinding()]

param(    )

BEGIN {
    $__PARAMETERMAP = @{}
    $__outputHandlers = @{
        Default = @{ StreamOutput = $False; Handler = { $args[0]| select-object -skip 1 | %{$n,$v,$p,$s = "$_" -split ' '; [pscustomobject]@{ Name = $n -replace '/now'; Version = $v; Architecture = $p; State = $s.Trim('[]') -split ',' } } } }
    }
}
PROCESS {
    $__commandArgs = @(
        "-q"
        "list"
        "--installed"
    )
    $__boundparms = $PSBoundParameters
    $MyInvocation.MyCommand.Parameters.Values.Where({$_.SwitchParameter -and $_.Name -notmatch "Debug|Whatif|Confirm|Verbose" -and ! $PSBoundParameters[$_.Name]}).ForEach({$PSBoundParameters[$_.Name] = [switch]::new($false)})
    if ($PSBoundParameters["Debug"]){wait-debugger}
    foreach ($paramName in $PSBoundParameters.Keys|Sort-Object {$__PARAMETERMAP[$_].OriginalPosition}) {
        $value = $PSBoundParameters[$paramName]
        $param = $__PARAMETERMAP[$paramName]
        if ($param) {
            if ( $value -is [switch] ) { $__commandArgs += $value.IsPresent ? $param.OriginalName : $param.DefaultMissingValue }
            elseif ( $param.NoGap ) { $__commandArgs += "{0}""{1}""" -f $param.OriginalName, $value }
            else { $__commandArgs += $param.OriginalName; $__commandArgs += $value |Foreach-Object {$_}}
        }
    }
    $__commandArgs = $__commandArgs|Where-Object {$_}
    if ($PSBoundParameters["Debug"]){wait-debugger}
    if ( $PSBoundParameters["Verbose"]) {
         Write-Verbose -Verbose -Message apt
         $__commandArgs | Write-Verbose -Verbose
    }
    $__handlerInfo = $__outputHandlers[$PSCmdlet.ParameterSetName]
    if (! $__handlerInfo ) {
        $__handlerInfo = $__outputHandlers["Default"] # Guaranteed to be present
    }
    $__handler = $__handlerInfo.Handler
    if ( $PSCmdlet.ShouldProcess("apt")) {
        if ( $__handlerInfo.StreamOutput ) {
            & "apt" $__commandArgs | & $__handler
        }
        else {
            $result = & "apt" $__commandArgs
            & $__handler $result
        }
    }
  } # end PROCESS

<#
.SYNOPSIS
Could not find apt to generate help.

.DESCRIPTION See help for apt

#>
}

Export-ModuleMember -Function Get-InstalledPackage
```

So first things first: can we get consistent about capitalization?
- Most of us don't capitalize _any_ keywords in PowerShell, and that includes `Function` and `BEGIN` ...
- Usually we choose a single capitalization style for variable names. I feel like we have a mix of ALL CAPS and camelCase here.

Secondly: can we get consistent about white space and line wrapping?
- Personally I prefer OTBS, although I know the Microsoft team, being mostly C# developers, have probably been conditioned to Alman, but this code does a crazy mix. It's _mostly_ K&R, but the first opening brace is on a new line, and then there's this weird if/elseif/else where each segment is on a single line (which doesn't match any of the rest of the code).
- There's a _lot_ of squeezing things onto one line in this, from the if/elseif/else block on lines 27..29 to the various `wait-debugger` lines (please tell me you don't intend to leave those in, in the final product?).
- There is even one line like this, where not only is the else on the same line with the code, but the code is actually two lines stuck together with a `;` for no real reason.
```PowerShell
else { $__commandArgs += $param.OriginalName; $__commandArgs += $value |Foreach-Object {$_}}
```
- There are _a lot_ of extra spaces inside parenthesis (not consistently enough to look intentional).
- Each line with a pipe | has a different number of spaces around it...
- Most of this can be fixed if I run the whole thing through PSScriptAnalyzer's formatter/fixers (especially if I turn on the options to fix aliases and capitalization). _Generated code **needs** to pass ScriptAnalyzer with flying colors_!

Third: can we get consistent about variable names?
- I assume there's a python programmer on the team, because of the `$__` ...
- I can see the value in prefixing the generated variables, to avoid the possibility of conflicting with the variable names used in the output handlers. However, if you're going to do that, you need to do it _religiously_, and you've missed `$value` and `$param` .. and `$paramname` and `$result`
- Personally, given that `$_` is the most common PowerShell variable, I don't like the double-underbar prefix, and I'd rather see you name the generated variables in a uniquely PowerShell way: `${Parameter Map}`, `${Output Handlers}`, `${Command Arguments}`, `${Bound Parameters}`, `${Parameter Value}` and `${Parameter Options}`.  This is equally unlikely to collide with user-chosen variables, and can't be confused with properties of `$_`

There are some other miscellaneous problems with the code currently:
- The variable '__boundparms' is assigned but never used (on line 20)
- The blog post said this would work in 5.1 but you're using ternary on line 27... 
- The (ab)use of `-Debug` to turn on Wait-Debugger is a little strange, to say the least. I don't think it's worth having in "production" code -- it'll just slow us down.
- Are we sure we want the "StreamOutput" to do `| & $handler` and not `| % $handler`? That's going to be faster, but will require a, uhm, certain level of sophistication from authors ... which is complicated by the fact that the _else_ case passes the parameters differently. Couldn't the non-streaming still pipe the input in, but after collecting it into a single `$result`, like: ` , $result | % $handler`

**Comment by theJasonHelmick** [comment]
Thanks @Jaykul !  These are great points and I will endeavor to improve the examples as we approach the next preview.  We did an update to remove the generation of the ternary operator (to support WinPS5.1) - however to your point I need to make sure they aren't in the examples.

**Comment by JamesWTruher** [comment]
sorry, i'm offended :) - this reason that this has the version number of `0.4.0` - i know there's a lot to do here, that's for picking on me.

**Comment by theJasonHelmick** [comment]
With the release of [Crescendo](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-general-availability-ga/), Style enhancements have been included. Please feel free to re-open this issue is continued discussion is desired.
