### ISSUE TITLE
Root command's options

### ISSUE THREAD

**Issue by matt9ucci** [PowerShell/Crescendo#30]
As of the current version [0.4.0](https://www.powershellgallery.com/packages/Microsoft.PowerShell.Crescendo/0.4.0), it seems that we can not make a cmdlet that has options between root command and sub command.

For example, `docker` command's `--log-level` option whose accepted values are `debug`, `info`, `warn`, `error`, and `fatal` (see: [docker cli reference](https://docs.docker.com/engine/reference/commandline/cli/)).

If we make `Build-DockerImage` cmdlet by `docker image build`, we will write the follwoing json for now:
```json
"OriginalName": "docker",
"OriginalCommandElements": [
    "image",
    "build"
], ...
```

But if `Debug` switch corresponding to `--log-level debug` is needed, we need the following features:
* To specify the `--log-level debug` as the original name and value of `Debug` switch, for example, `OriginalNameAndValue` in the below json
* To insert the `--log-level debug` between `docker` and `image` like `docker --log-level debug image build`
```json
"Parameters": [
    {
        "Name" : "Debug",
        "ParameterType" : "switch",
        "OriginalNameAndValue" : "--log-level debug" // <-- inserted between `docker` and `image`
    }
], ...
```

**Comment by Jaykul** [comment]
This is critical, because docker (and others) will only accept those options _before_ the command

**Comment by theJasonHelmick** [comment]
Interesting, so to be clear, your proposing that `OriginalNameAndValue` be available in each parameter similar to `OriginalCommandElements`?

**Comment by matt9ucci** [comment]
> OriginalNameAndValue be available in each parameter similar to OriginalCommandElements?

Yes, but currently I am not sure that is a good idea. I think it depends on how to resolve the another problem: "To insert the `--log-level debug` between `docker` and `image` like `docker --log-level debug image build`".
One of my idea is to allow powershell-like string format such as `"OriginalName": "docker {0} {1}"`. The `{0}` and `{1}` can be replaced with `"SomeReplaceableItems" : [ "--log-level debug", "--foo bar" ]`.

**Comment by theJasonHelmick** [comment]
We are investigating how to approach this as it seems reasonable and we agree that this should be included. I will post back with additional information/questions.

**Comment by comnam90** [comment]
Any updates on this one? :)

**Comment by theJasonHelmick** [comment]
thank you @matt9ucci - This is possible through the Parameter attribute **ApplyToExecutable**.  This is currently not in the schema and won't get prompted, but it is part of the object model and can use it.  This was added for V1.0.
