### ISSUE TITLE
Gap character parameter

### ISSUE THREAD

**Issue by cdhunt** [PowerShell/Crescendo#32]
Instead of the NoGap bool, it would be more useful to have a gap character property. By default, it would be a space but could be an empty string or a colon or whatever separator is needed.

**Comment by theJasonHelmick** [comment]
Hey @cdhunt!  Do you have an example/scenario for the gap character need?

**Comment by cdhunt** [comment]
[Terraform](https://www.terraform.io/docs/commands/apply.html) uses `=`. The 1password `op` cli also uses `=` for a [particular flavor of argument](https://support.1password.com/command-line/#create-or-edit-an-item). I'm pretty sure I've seen a `:` used, but I don't remember what binary that was.

**Comment by theJasonHelmick** [comment]
We agree that it should be configurable and are considering this for preview 3.

**Comment by JamesWTruher** [comment]
@cdhunt I think this is possible today by simply having the original parameter include the gap character. So you can define the originalparameter as `foo=` or `bar:` and set nogap. Is this sufficient?

**Comment by cdhunt** [comment]
That works.

**Comment by theJasonHelmick** [comment]
thanks @cdhunt
