### ISSUE TITLE
OutputHandlers has support for external scripts

### ISSUE THREAD

**Issue by cdhunt** [PowerShell/Crescendo#33]
Doing anything beyond a one-liner in the `Handler` property is extremely error-prone. Even simple typos aren't picked up because it's just a string value. It would be useful if there was a `HandlerPath` property that would pull in code from a script file. That would make any reasonably complex hander logic easier to maintain.

**Comment by theJasonHelmick** [comment]
@cdhunt - We have talked about this and are investigating.  I want to see if we can improve the output handler to make it easier for common scenarios - perhaps removing the need to have a separate script file in many cases, but I can see where this still might be useful.

**Comment by webtroter** [comment]
+1
If I could add a function, and call this function in the handler, that would help a lot.

If it helps understanding my process : 
I wrote the Crescendo JSON as a powershell ordered hashtable in a ps1 script, and I generate the JSON from that script. I'd like to add function written in this PS1 to the final Crescendo Module.

**Comment by theJasonHelmick** [comment]
This feature is added starting with preview 3.  There are three methods of working with output handlers.  Inline, Function and Script.

**Comment by theJasonHelmick** [comment]
Thank you - This issue has been addressed in Preview.3
