### ISSUE TITLE
Credential Parameters

### ISSUE THREAD

**Issue by realslacker** [PowerShell/Crescendo#34]
There should be a way to have a Credential parameter that can automatically be applied to UserName/Password, possibly Domain/UserName/Password.

For example something like Invoke-NetUse -Share '\\server\share' -DriveLetter 'D:' -Credential (Get-Credential DOMAIN\UserName) should execute the native net.exe like this:

```
net.exe use D: \\server\share /username:DOMAIN\UserName<ENTER>
Enter the password for 'METHODE-GLOBAL\admin.sg503689' to connect to 'cncn01-fs01.methode.global': <password><ENTER>
```

The idea being that we limit the amount of time the plaintext password is in memory and prevent a plain text password from being entered into the console.

**Comment by theJasonHelmick** [comment]
This is certainly a reasonable request that we are beginning to investigate and will look at for Preview2, but it may require more work.

**Comment by jdhitsolutions** [comment]
This has to be a requirement. With the current version, I can't figure out how to have the PowerShell command use a Credential and split it into username and password so that the native command can use it.

**Comment by B-Art** [comment]
> This has to be a requirement. With the current version, I can't figure out how to have the PowerShell command use a Credential and split it into username and password so that the native command can use it.

Did you mean this:
```
$a=Get-Credential
$a.UserName
$a.Password | ConvertFrom-SecureString
```

Username is simple.
Password I do not know rigth now.

```
$a | gm

   TypeName: System.Management.Automation.PSCredential

Name                 MemberType Definition
----                 ---------- ----------
Equals               Method     bool Equals(System.Object obj)
GetHashCode          Method     int GetHashCode()
GetNetworkCredential Method     System.Net.NetworkCredential GetNetworkCredential()
GetObjectData        Method     void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context), void ISerializable.GetObjectData(System.Runtime…
GetType              Method     type GetType()
ToString             Method     string ToString()
Password             Property   securestring Password {get;}
UserName             Property   string UserName {get;}
```

**Comment by realslacker** [comment]
@B-Art to me the problem is not using the credential object, but rather providing it as a parameter in the first place.

**Comment by B-Art** [comment]
> @B-Art to me the problem is not using the credential object, but rather providing it as a parameter in the first place.

But if you the -credential $a that works fine.
You don't have to split it upfront.

**Comment by realslacker** [comment]
It's been a while since I have tried Crescendo, I had some issues and gave up... but maybe it's time to take another look.

**Comment by theJasonHelmick** [comment]
Command elevation has been added to [Crescendo Preview 2](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-2/).  Try the 1.0 release of [Crescendo](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-general-availability-ga/), and feel free to provide additional feedback on elevation.
