### ISSUE TITLE
Handling native positional parameters

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/Crescendo#35]
It isn't clear to me if there is a way to handle positional parameters in native commands. For example, the ARP command has a positional parameter value for in Internet address, among others. How would I reference that? I've tried looking through documentation but can't find an easy to understand explanation. Or has this not been addressed yet?

**Comment by theJasonHelmick** [comment]
@jdhitsolutions, this is something we have been discussing.  There is a `position` property in the schema for parameters for this purpose.  I don't have a posted example of this yet, but you could give that a try.

**Comment by theJasonHelmick** [comment]
This is handled today. Take a look at the ls example.
