### ISSUE TITLE
Introduce support for all parameter validation options

### ISSUE THREAD

**Issue by lucdekens** [PowerShell/Crescendo#38]
Perhaps it is already there, but I couldn't find it.
Supporting all parameter validation options would be a handy feature.

**Comment by theJasonHelmick** [comment]
We agree @lucdekens , and this is supported today though I suspect we have some work to do here. If you take a look under the Test/Assests folder you will find this sample: https://github.com/PowerShell/Crescendo/blob/master/Microsoft.PowerShell.Crescendo/test/assets/FullProxy.json

Note the parameter section below "AdditionalParameterAttributes".

```json
    "Parameters": [

        {
            "Name": "Parameter1",
            "OriginalName": "--parameter1",
            "Description": "param1 description",
            "Mandatory": true,
            "ParameterSetName": [ "pset1" ],
            "Aliases": [ "a1" ],
            "ParameterType": "string",
            "AdditionalParameterAttributes": [
                "[ValidateSet('one','two')]",
                "[ValidateLength(1,10)]"
            ]

```

**Comment by theJasonHelmick** [comment]
Thank you - This issue has been addressed in Preview.2.
