### ISSUE TITLE
Add an option to check if requirements are met to run a command

### ISSUE THREAD

**Issue by lucdekens** [PowerShell/Crescendo#39]
Some commands need an elevated prompt or need to be run from a specific account, or need specific conditions to be met.

It would be handy to have an option that would add something like
```
#Requires -RunAsAdministrator
```
to the code in the generated module.

Or perhaps an option to add a user-provided code block where one can test if specific conditions are met.

**Comment by theJasonHelmick** [comment]
Command elevation has been added to [Crescendo Preview 2](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-2/). Try the 1.0 release of [Crescendo](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-general-availability-ga/), and feel free to provide additional feedback on elevation.
