### ISSUE TITLE
PowerShell Crescendo json files should support multiple native command definitions

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/Crescendo#49]
PowerShell Crescendo currently supports generating multiple json files into a single PowerShell module.

```powershell
Export-CrescendoModule -ConfigurationFile .\get-ipconfig.proxy.json,.\Remove-ipconfig.proxy.json,.\New-ipconfig.proxy.json -ModuleName ./ipconfig.psm1
```

- It would be easier to develop and maintain multiple native commands in a single json file. 
- Crescendo should support both linux and windows native commands in the same json file.

_Originally posted by @theJasonHelmick in https://github.com/PowerShell/Crescendo/discussions/45_

**Comment by jdhitsolutions** [comment]
I think has to be a requirement.

**Comment by theJasonHelmick** [comment]
This feature is added starting with preview 3.

**Comment by theJasonHelmick** [comment]
Thank you - This issue has been addressed in Preview.3
