### ISSUE TITLE
Sudo/Runas support for PowerShell Crescendo

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/Crescendo#50]
In many cases when working with native commands, a change to the elevation level is required to achieve the expected results on either Linux or Windows systems. As an example, on a linux system the sudo command changes elevation and the results of the native command:

```powershell
> whoami
> JasonHelmick
```

```powershell
> sudo whoami
> Root
```

We are thinking of how best to support the elevation needs of native commands with PowerShell Crescendo.  Below is an example of how this might be written into the json file.

{
    "$schema" : "./Microsoft.PowerShell.Crescendo.Schema.json",
    "Verb": "Invoke",
    "Noun": "whoami",
    "OriginalName":"/usr/bin/whoami",
    "ElevationCommand": {
        "Command": "sudo"
    }
}

The  json could also would support arguments passed to the elevation command, similar to this:

"ElevationCommand": "command",
"Arguments": [
"arg1",
"arg2"
]

First, would appreciate feedback on handling elevation and the above example. 
Also, based on the discussion #45 (PowerShell Crescendo json files should support multiple native commands)
- should we support both linux and Windows elevation in the same json 
- if so, what scenarios do you see this addressing?

_Originally posted by @theJasonHelmick in https://github.com/PowerShell/Crescendo/discussions/47_

**Comment by theJasonHelmick** [comment]
This feature is released starting with preview 2.

**Comment by mi-hol** [comment]
great news!

**Comment by theJasonHelmick** [comment]
Thank you - This issue has been addressed in Preview.2.
