### ISSUE TITLE
Crescendo should export .psd1 with .psm1

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/Crescendo#51]
PowerShell Crescendo exports a module `.psm1` containing the crescendo proxy functions that enable easier administration and automation of native commands.  `Export-CrescendoModule` should include and export a module manifest `.psd1` for the following reasons:

* Best practice to include a manifest with the Module
* Authors will be able to version the module, specify files in the module (such as nested modules), run scripts to customize the user's environment, load type and formatting files, define system requirements, and limit the members that the module exports

In addition, add PowerShell Gallery tag to module manifest private data
* Add a PowerShell Gallery tag to the private data section of the module manifest to allow customers to quickly filter and recognize Crescendo generated modules on PSGallery.
* Tag: Crescendo

**Comment by ethanbergstrom** [comment]
While generating a new module manifest automatically is great, what's generated now with 0.5.1 is bloated with comments and overwrites a manifest that may already exist, which is problematic for project owners that already manage a tailored and versioned manifest in source control, such as with https://github.com/ethanbergstrom/Foil/blob/master/src/Foil.psd1

A flag to suppress automatic manifest creation would be nice. I've had to [pin Foil to Cresendo 0.4.1](https://github.com/ethanbergstrom/Foil/blob/master/appveyor.yml#L10) in the meantime.

**Comment by theJasonHelmick** [comment]
Thank you - This issue has been addressed in Preview.2.
