### ISSUE TITLE
Executable Versions with different inputs / outputs 

### ISSUE THREAD

**Issue by smurawski** [PowerShell/Crescendo#53]
Given command output and arguments/switches can change between versions, Crescendo should support multiple candidate versions.  When the executable can return a version - in an automated fashion, and where not perhaps a disclaimer.

cc @theJasonHelmick

**Comment by theJasonHelmick** [comment]
@smurawski - How would you expect this to work - would you expect that Crescendo runs the command and from a table determine the correct version and then build the proxy -- or, would you expect Crescendo to determine the version and then choose the correct proxy from a list of proxies built in the module.  This is a little tricky and we need to understand better.
