### ISSUE TITLE
Schema location

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/Crescendo#55]
For testing purposes, I downloaded the schema and use a relative path in my son.

```
 "$schema": "./Microsoft.PowerShell.Crescendo.Schema.json",
```

But should this eventually be an online reference? And if so, has it been set? Or do we reference it from this repo?

**Comment by JamesWTruher** [comment]
yah - the plan is that it will wind up online, but not until we get closer to a real V1
