### ISSUE TITLE
Don't show OriginalCommand in help example unless specified

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/Crescendo#57]
When defining an Example in the JSON file, if I omit the OriginalCommand entry, I don't want to see an entry for it in the final help.

![image](https://user-images.githubusercontent.com/12089920/106329364-49801000-624f-11eb-9b93-b2675ec29cf5.png)

**Comment by theJasonHelmick** [comment]
This looks like a reasonable request and we will take a look.

**Comment by JamesWTruher** [comment]
fixed in commit 84c597f7d32605394a01a7ce3990add033aa08e1
