### ISSUE TITLE
Export-CrescendoModule has odd support for -WhatIf

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/Crescendo#59]
With most PowerShell commands, if you call a command inside a function that supports should process, the preference is passed to the underlying command.

```powershell
function foo-test {
 [cmdletbinding(SupportsShouldProcess)]
param($name)
Stop-Service $name
}

foo-test bits -WhatIf
What if: Performing the operation "Stop-Service" on target "Background Intelligent Transfer Service (bits)".
```

But when `Export-CrescendoModule` is used, it doesn't appear to pickup SupportsShouldProcerss. Yet, the command will recognize it when used directly:

```powershell
Export-CrescendoModule -ConfigurationFile .\CmdKey-crescendo.json -modulename foo -WhatIf

What if: Performing the operation "Output to File" on target "foo.psm1".
What if: Performing the operation "Output to File" on target "foo.psm1".
What if: Performing the operation "Output to File" on target "foo.psm1".
```

Although oddly, it appears to be writing the file 3 times.

**Comment by JamesWTruher** [comment]
The reason this happens 3 times is a side effect of how the `.psm1` file is created (multiple redirection). It's a bit clunky and I'll take a look at cleaning this code up.

**Comment by jdhitsolutions** [comment]
I'm still hoping this will be merged with a few other open issues such as having multiple definitions in a single json file. I'd love to have a process where I create the crescendo json, and the "conversion" process creates a function file for each command, a psm1 file that dot sources the files, and a manifest.

**Comment by theJasonHelmick** [comment]
Thank you - This issue has been addressed in Preview.2.
