### ISSUE TITLE
Question: What does "OriginalText" do ?

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/Crescendo#67]
Crescendo json schema do have a `OriginalText` outside of `Usage` but it doesn't have any description showing where its used, neither consumed in the crescendo module generation code.

**Comment by theJasonHelmick** [comment]
I hovered over "OriginalText" and received the following (See graphic). So, I would agree that the name OriginalText may not be as descriptive as "OriginalCommandHelpText" or "OriginalCommandHelp", but prefer the terse nature of the name.  We feel that the tooltip provides adequate information.
<img width="518" alt="Screen Shot 2021-03-09 at 3 37 14 PM" src="https://user-images.githubusercontent.com/12662278/110553158-6c72cf00-80ed-11eb-8043-d795d80fc6a1.png">

**Comment by theJasonHelmick** [comment]
Hey @kvprasoon - have you had a chance to try this under preview 4?  With the new Schema and some fixes that we started in Preview 3, wanted to see if your experience is the same.
