### ISSUE TITLE
Crescendo should have a parameter property for SupportsWildCards() attribute

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/Crescendo#79]
The native command parameters may support wildcard input. For those cases, the parameter for the Crescendo-generated cmdlet should use the SupportsWildcards() attribute.

This is required for proper documentation of the cmdlet using PlatyPS.

**Comment by theJasonHelmick** [comment]
This is supported today by adding SupportsWildCards to the `AdditionalParameterAttributes` section of the schema.  While adding the attribute to the schema is fairly simple, it would require additional underlying code to resolve the semantics of Wildcards to the native command. Today we simply pass the wildcards to the native commands. 

What would be the specific impact to the documentation without the attribute considering many Authors may not think about including it?

**Comment by sdwheeler** [comment]
PlatyPS would show that the parameter does not support wildcards when it actually does. The attribute should be used (where applicable) for all Crescendo modules that Microsoft publishes. We need to provide good examples showing this attribute in the configuration and it needs to be documented.

**Comment by theJasonHelmick** [comment]
Thank you - This issue has been addressed in Preview.3
