### ISSUE TITLE
ReadMe mixed up words

### ISSUE THREAD

**Issue by M1kep** [PowerShell/Crescendo#84]
*Submitting as issue as it is indicated that PRs are not accepted currently.

While reading the readme I can across the following:

> The Microsoft.PowerShell.Crescendo module provides a way to more easily for native commands to participate in the PowerShell pipeline by facilitating parameter handling...

I believe this should be:

> The Microsoft.PowerShell.Crescendo module provides native commands a way to more easily participate in the PowerShell pipeline by facilitating parameter handling...

**Comment by theJasonHelmick** [comment]
Thanks @M1kep for catching my mistake ;). You are correct and I will get this updated.

**Comment by theJasonHelmick** [comment]
The readme is updated based on this pr https://github.com/PowerShell/Crescendo/pull/85
