### ISSUE TITLE
Create object wrappers for core GNU/*nix utilities

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/Crescendo#88]
This got brought up during the sync with azure-cli. It would be awesome to have some kind of wrappers for core GNU/*nix management tools (e.g. ifconfig, iptables, etc.) so that you can manipulate the output of these tools as if they were PS cmdlets. 

So, for instance, where `ifconfig` might return:

```
eth0 Link encap:Ethernet HWaddr 00:0C:29:40:93:9C
     inet addr:192.168.154.102 Bcast:192.168.154.255 Mask:255.255.255.0
     UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
     RX packets:1771 errors:0 dropped:0 overruns:0 frame:0
     TX packets:359 errors:0 dropped:0 overruns:0 carrier:0
     collisions:0 txqueuelen:1000
     RX bytes:138184 (134.9 KiB) TX bytes:49108 (47.9 KiB)
     Interrupt:67 Base address:0x2000
```

`Get-Ifconfig` might return an object that includes properties like `inetaddr`, `Bcast`, and `Mask`. Even if these are all strings, I imagine it could actually entice a beginner to intermediate *nix admin to use PowerShell for scripting against tools that may have better core networking/storage/etc support than .NET-based cmdlets.

**Comment by theJasonHelmick** [comment]
With the release of [Crescendo](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-general-availability-ga/), Users can now wrap any platform specific command for a more PowerShell cmdlet-like experience including object based output.  With this accelerator, the PowerShell community can build and share PowerShell modules containing linux and windows commands.  For detailed information, see the [Crescendo docs](https://docs.microsoft.com/en-us/powershell/utility-modules/crescendo/overview?view=ps-modules).
