### ISSUE TITLE
Help files should have some examples

### ISSUE THREAD

**Issue by Cheffromspace** [PowerShell/Crescendo#98]
Things I build for myself that I never plan to share with anyone are better documented than this.  

I guess the 'New' commands are supposed to help create the json, and we're supposed to nest accordingly and output to a file? I don't understand how to create a valid json using the commands provided.  Am I supposed to create the json scaffolding by hand?

**Comment by theJasonHelmick** [comment]
@Cheffromspace - thanks for filing the issue.  We do have plans to look at tooling (cmdlet support) during our next preview.  The commands currently have been stubs and mainly experimental.  Having said that, yes, its best to create a scaffold of the json, or copy one from the Sample folder in the module, to get started.  We will have more information about the tooling we will include for GA as we approach preview.4 over the next month.  I would agree that  having a simple way to create the scaffold for commands - something like New-CrescendoCommand to autogenerate the json - should be included.

**Comment by theJasonHelmick** [comment]
Completed as of general availability. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.crescendo/?view=ps-modules
